name: all

on: [push]

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - run: apk add pacman go gcc fakeroot runuser
      - run: adduser -D actions
      - run: runuser -u actions -- go test -v .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --tag ghcr.io/afq984/repo-add-http
        env:
          DOCKER_BUILDKIT: '1'
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        if: ${{ github.ref == 'refs/heads/main' }}
      - run: docker push ghcr.io/afq984/repo-add-http:latest
        if: ${{ github.ref == 'refs/heads/main' }}
