name: all

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - run: apk add pacman go gcc fakeroot runuser
      - run: adduser -D actions
      - run: runuser -u actions -- go test -v .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --tag ghcr.io/afq984/repo-add-http
        env:
          DOCKER_BUILDKIT: '1'
      - run: echo $GHCR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
            GHCR_PAT: ${{ secrets.GHCR_PAT }}
        if: ${{ github.ref == 'refs/heads/main' }}
      - run: docker push ghcr.io/afq984/repo-add-http:latest
        if: ${{ github.ref == 'refs/heads/main' }}
