name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - run: apk add pacman go gcc fakeroot runuser
      - run: adduser -D actions
      - run: runuser -u actions -- go test -v .
